CREATE TABLE IF NOT EXISTS Books (
    BookID INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT NOT NULL,
    Author TEXT NOT NULL,
    ISBN TEXT NOT NULL UNIQUE,
    YearPublished INTEGER NOT NULL,
    Genre TEXT NOT NULL,
    IsBorrowed INTEGER NOT NULL DEFAULT 0
);